Vagrant.configure("2") do |config|
  config.vm.box = "sanjay900/jdk-12"
  config.vm.network "forwarded_port", guest: <port>, host: <port>
  config.vm.network "forwarded_port", guest: <port2>, host: <port2>
  config.vm.provision "file", source: "<source>", destination: "safeNativeCode.jar"
  config.vm.provision :shell, inline: "nohup sh -c '<javaCommand>;sudo systemctl --force --force poweroff' 0<&- &>out.log &", run: 'always'
end
